### ISSUE TITLE
Node version requirement

### ISSUE THREAD

**Issue by jdcodenoise** [kato-im/hubot-kato#8]
When I was running the current version of Node.js (0.12.x) I was getting this error: 

```console
Error: "name" and "value" are required for setHeader().
  at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:333:11)
  at new ClientRequest (_http_client.js:101:14)
  at Object.exports.request (http.js:49:10)
  at Object.exports.request (https.js:136:15)
  at KatoClient.request (/Users/jdbailey/workspace/codenoise-hubot/node_modules/hubot-kato/src/kato.coffee:276:40, <js>:375:24)
  at KatoClient.put (/Users/jdbailey/workspace/codenoise-hubot/node_modules/hubot-kato/src/kato.coffee:243:5, :338:19)
  at KatoClient.Login (/Users/jdbailey/workspace/codenoise-hubot/node_modules/hubot-kato/src/kato.coffee:138:5, :197:19)
  at Kato.run (/Users/jdbailey/workspace/codenoise-hubot/node_modules/hubot-kato/src/kato.coffee:85:5, :125:14)
  at Robot.run (/Users/jdbailey/workspace/codenoise-hubot/node_modules/hubot/src/robot.coffee:443:5, :396:27)
  at Object. (/Users/jdbailey/workspace/codenoise-hubot/node_modules/hubot/bin/hubot:135:8, :146:11)
  at Object. (/Users/jdbailey/workspace/codenoise-hubot/node_modules/hubot/bin/hubot:5:1, :149:4)
  at Module._compile (module.js:460:26)
```

Running the shell adapter worked fine, just would get this error every time I tried to use the kato adapter. After much fiddling, I have deduced that this is a problem with my node version. I was able to get everything running right on my other machine under node 0.10.x, so I downgraded and am up and running. I wasn't able to determine if the problem was in your adapter or in the bot as a whole, but I thought you guys might be able to make something of it.

**Comment by abs** [comment]
Thanks, we'll take a look!

**Comment by JLarky** [comment]
@jdcodenoise please take a look at version 0.1.1 did it help?
